// Back-office ("Console") look: quiet Apple-style neutrals with one blue accent.
// Scoped to the back office only — the public site keeps COLOR.primary (#337ab7).
export const BO = {
  canvas: "#f5f5f7",
  surface: "#ffffff",
  surfaceAlt: "#fbfbfd",
  hover: "rgba(0, 0, 0, 0.04)",
  text: "#1d1d1f",
  textSecondary: "#424245",
  textTertiary: "#6e6e73",
  textDisabled: "#a1a1a6",
  primary: "#0071e3",
  primaryHover: "#0077ed",
  primaryActive: "#005bbf",
  primarySoft: "#f0f6ff",
  success: "#34c759",
  successText: "#1d7c34",
  warning: "#ff9f0a",
  error: "#ff3b30",
  border: "#d2d2d7",
  separator: "#e5e5ea",
};

export const backOfficeTheme = {
  token: {
    colorPrimary: BO.primary,
    colorInfo: BO.primary,
    colorLink: BO.primary,
    colorSuccess: BO.success,
    colorWarning: BO.warning,
    colorError: BO.error,
    colorText: BO.text,
    colorTextSecondary: BO.textTertiary,
    colorTextTertiary: BO.textTertiary,
    colorTextPlaceholder: BO.textTertiary,
    colorBorder: BO.border,
    colorBorderSecondary: BO.separator,
    colorBgLayout: BO.canvas,
    colorFillAlter: BO.surfaceAlt,
    borderRadius: 8,
    borderRadiusLG: 16,
    borderRadiusSM: 6,
    controlHeight: 40,
    controlOutline: "rgba(0, 113, 227, 0.25)",
    controlOutlineWidth: 3,
    boxShadowSecondary: "0 4px 12px rgba(0, 0, 0, 0.08), 0 1px 3px rgba(0, 0, 0, 0.04)",
  },
  components: {
    Table: {
      headerBg: BO.surfaceAlt,
      headerColor: BO.textSecondary,
      headerSplitColor: "transparent",
      borderColor: BO.separator,
      headerBorderRadius: 0,
      cellPaddingBlock: 14,
      rowHoverBg: "rgba(0, 0, 0, 0.015)",
      fontWeightStrong: 600,
    },
    Button: {
      borderRadius: 8,
      controlHeight: 40,
      fontWeight: 600,
      primaryShadow: "none",
      defaultShadow: "none",
      dangerShadow: "none",
      defaultBorderColor: BO.border,
      defaultColor: BO.text,
    },
    Card: {
      borderRadiusLG: 16,
      colorBorderSecondary: BO.separator,
      headerFontSize: 16,
    },
    Input: { borderRadius: 8, controlHeight: 42, activeShadow: "0 0 0 3px rgba(0, 113, 227, 0.25)" },
    InputNumber: { borderRadius: 8, controlHeight: 42, activeShadow: "0 0 0 3px rgba(0, 113, 227, 0.25)" },
    Select: { borderRadius: 8, controlHeight: 42, optionSelectedBg: BO.primarySoft },
    DatePicker: { borderRadius: 8, controlHeight: 42, activeShadow: "0 0 0 3px rgba(0, 113, 227, 0.25)" },
    Pagination: {
      borderRadius: 8,
      itemSize: 36,
      itemActiveBg: BO.primary,
      itemActiveColor: "#ffffff",
      itemActiveColorHover: "#ffffff",
      itemActiveBgDisabled: BO.separator,
    },
    Modal: { borderRadiusLG: 20 },
    Drawer: { colorBgElevated: BO.surface },
    Tabs: { horizontalItemGutter: 28, itemColor: BO.textSecondary, itemSelectedColor: BO.text, inkBarColor: BO.primary },
    Tag: { borderRadiusSM: 9999 },
    Segmented: { borderRadius: 8, trackBg: BO.separator, itemSelectedColor: BO.text },
    Switch: { colorPrimary: BO.primary, colorPrimaryHover: BO.primaryHover },
    Checkbox: { borderRadiusSM: 5 },
    Dropdown: { borderRadiusLG: 12 },
    Menu: {
      itemBg: "transparent",
      subMenuItemBg: "transparent",
      itemColor: BO.textSecondary,
      itemHoverColor: BO.text,
      itemHoverBg: BO.hover,
      itemSelectedColor: BO.primary,
      itemSelectedBg: "rgba(0, 113, 227, 0.1)",
      itemActiveBg: BO.hover,
      itemBorderRadius: 10,
      itemMarginInline: 8,
      itemMarginBlock: 2,
      itemHeight: 40,
      iconSize: 16,
      collapsedIconSize: 18,
      groupTitleColor: BO.textTertiary,
      groupTitleFontSize: 11,
    },
  },
};
